name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/llm-linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
